### ISSUE TITLE
Warm-up volunteer badge has got AWOL

### ISSUE THREAD

**Issue by pwhettlock** [fraz3alpha/running-challenges#377] opened 2023-04-03 15:59 UTC
parkrun look to have removed " (junior events only)" from the description of "Warm Up Leader". Not seen any announcements about warm-ups being extended to non-junior events - so possibly just a tweak to the name.

**Comment by fraz3alpha** [comment] 2023-04-15 20:00
List of parkrunner IDs of people who have emailed to say this is missing:

- 1731148

ok, hardly a list, it's one person, there are several more who just emailed to say it was missing and gave us nothing to go on to check :(

**Comment by pwhettlock** [comment] 2023-04-16 06:39
Happy to be added to the list: 88720 

Have done all but one volunteer role - lead bike, and now that's gone.

**Comment by fraz3alpha** [comment] 2023-04-16 06:47
I added your change to another branch last night where I added a test to
check the other user was awarded the badge - I think it only fixed English
language sites, so I'll look at it again tonight.

Your parkrunner Id will be useful if you've done practically all of them!

**Comment by LukeWoodward** [comment] 2023-04-16 13:21
I can confirm this role has gone missing for me as well. I've now done this role 10 times, including once this morning. In case it helps, my parkrun ID is A3920799.

**Comment by fraz3alpha** [comment] 2023-04-16 14:05
Luke, it's not specific to a certain person, it's the name of the role that
changed and it doesn't match for anyone right now

**Comment by LukeWoodward** [comment] 2023-04-16 19:14
@fraz3alpha I agree. I guess I interpreted your comment yesterday as a lament that not many people reporting this problem had shared their parkrunner ID with you and that having more of them would be helpful, hence why I provided mine.

**Comment by fraz3alpha** [comment] 2023-04-16 19:35
Hi Luke, no worries.
Sorry, I think I was being a little grumpy last night - we've have quite a lot of people say that something isn't working for them via email and in 90% of cases they never provide any extra information so that we can even check what they see, or know what they've configured in their settings.

I made @pwhettlock's change in a branch last night, but it still failed for some parkrun sites, so I believe that it might actually need a change for each language - or at least some languages, still need to some more checking so we can fix it for all.

The good news is that I did the test for a single parkrunner ID and tried it on all the sites, and they seem to have the roles listed in the various languages, so I perhaps don't need an example of a person from each country. We'll see.

**Comment by pwhettlock** [comment] 2023-04-17 13:20
In terms of IDs for volunteer badges, the following person has the rare Lead Bike one - 2705084

**Comment by fraz3alpha** [comment] 2023-04-17 20:43
@pwhettlock , I don't know if you've looked at your page on the Japanese site, but you've done "Do Not Translate" 14 times :) 

https://www.parkrun.jp/parkrunner/88720/

![Screenshot from 2023-04-17 21-41-36](https://user-images.githubusercontent.com/2786011/232606147-45fc5d9c-ff94-4150-85fd-e8cfe0bd20ec.png)

-which is backup timer, which was done away with in preference for everyone just being timers :) 

(and parkwalker appears not to have been translated, but is at least right)

**Comment by pwhettlock** [comment] 2023-04-18 06:47
@fraz3alpha no, haven't visited there before.

Did notice that I'd done "(not applicable to parkrun Germany)" though! (Which is Warm-up Leader)

![image](https://user-images.githubusercontent.com/74610113/232693834-363e7af6-12ea-465d-b17b-ddb77a019092.png)

**Comment by fraz3alpha** [comment] 2023-04-18 19:33
If anyone wants to try it, the extensions attached to this build should give the Warm-up Volunteer badge back: https://github.com/fraz3alpha/running-challenges/actions/runs/4732021952

**Comment by pwhettlock** [comment] 2023-04-19 06:41
![image](https://user-images.githubusercontent.com/74610113/232988118-8c044dde-6972-448c-827b-7b9b7822e45d.png)

**Comment by LukeWoodward** [comment] 2023-04-22 15:57
I can confirm the latest build works for me too. The Warm-up Leader badge is back and the extension reports my v-index as 10.

**Comment by johnsyweb** [comment] 2023-05-13 05:33
Also confirming that the extensions attached to this build give the Warm-up Volunteer badge back: https://github.com/fraz3alpha/running-challenges/actions/runs/4732021952

Verified with my profile: https://www.parkrun.com.au/parkrunner/1001388/all/

Thanks all.

**Comment by fraz3alpha** [comment] 2023-06-30 07:37
Fixed in v1.4.0, uploaded yesterday. Seems to be available in Chrome and Firefox now

**Closed by fraz3alpha** 2023-06-30 07:37 UTC
Labels: fix-committed
