### ISSUE TITLE
The "name badge" achievement now adds in the Parkrun number

### ISSUE THREAD

**Issue by solarisfire** [fraz3alpha/running-challenges#369] opened 2023-02-04 18:40 UTC
The "name badge" achievement now adds in the Parkrun number (A1234567)... Not sure if any parkruns exist starting with numbers or the characters ( or ).

![image](https://user-images.githubusercontent.com/420952/216784059-f0904e49-1af4-41fd-8dc6-b273555ce9b7.png)

**Comment by fraz3alpha** [comment] 2023-02-04 18:48
Oh, that doesn't look right!

**Comment by solarisfire** [comment] 2023-02-04 20:26
I just threw in a pull request that fixes this.

**Comment by fraz3alpha** [comment] 2023-04-06 20:36
FYI, the code has always removed characters that you can't get - so it doesn't require you to get a `(` and the numbers, but it does ask you get an extra `a`. So perhaps some people will temporarily lose this badge until the fix is released e.g.

![Screenshot from 2023-04-06 21-35-59](https://user-images.githubusercontent.com/2786011/230488897-878e88be-d450-4988-8c75-2c94b75e2847.png)

**Comment by fraz3alpha** [comment] 2023-04-18 19:35
If anyone wants to try it, the extensions attached to this build should contain the above fix to correct this: https://github.com/fraz3alpha/running-challenges/actions/runs/4732021952

**Comment by pwhettlock** [comment] 2023-04-19 06:49
![image](https://user-images.githubusercontent.com/74610113/232989850-76e8f27a-f2d7-4de4-8f3c-304d2886cc85.png)

**Comment by johnsyweb** [comment] 2023-05-25 12:52
Confirmed.

**Comment by fraz3alpha** [comment] 2023-06-30 07:37
Fixed in v1.4.0, uploaded yesterday. Seems to be available in Chrome and Firefox now

**Closed by fraz3alpha** 2023-06-30 07:37 UTC
Labels: fix-committed
